export interface UserInterface {
  id: number;
  commission_id?: string;
  entity_internal_id?: number;
  entity_code?: string;
  created_at?: string;
  updated_at?: string;
  name: string;
  company: string;
  location: string;
  mobile: string;
  commission?: string;
  info?: string;
  date?: string;
  status?: string;
  stage?: string;
  field?: string;
  email?: string;
  website?: string;
  address?: string;
  notes?: string;
  assigned_to?: string;
  assigned_user_ids?: number[];
  last_contact?: string;
  next_step?: string;
  priority?: string;
  tags?: string[];
  activity_scope?: string;
  activity_item_id?: string | number;
  activity_latest_at?: string;
  activity_created_at?: string;
}
