window.GROUPED_FIELD_OPTIONS = [
  {
    label: "IT, Technologie a Data",
    options: [
      "Automatizace",
      "Civic Tech (technologie pro občany a stát)",
      "Čisté technologie",
      "Datová analytika",
      "Digitální technologie / IT služby",
      "Etika v technologiích",
      "Fintech",
      "Geoinformatika",
      "Informatika",
      "Informatika a vývoj software",
      "Kyberbezpečnost",
      "Nanotechnologie",
      "Počítačové vědy",
      "Programování",
      "Quantum computing (kvantové výpočty)",
      "Robotika a automatizace",
      "Softwarové inženýrství",
      "Statistika a analýza dat",
      "Systémové inženýrství",
      "Technologie umělé inteligence",
      "Telekomunikace",
      "Testování softwaru",
      "Tvorba her (game design)",
      "Umělá inteligence (AI)",
      "Webdesign",
      "Vývoj software"
    ]
  },
  {
    label: "Průmysl, Inženýrství a Výroba",
    options: [
      "Aeronautika a letectví",
      "Automobilový průmysl",
      "Civilní inženýrství",
      "Chemická technologie",
      "Chemické inženýrství",
      "Chemie a chemický průmysl",
      "Dřevozpracující průmysl",
      "Elektrotechnika",
      "Energetika (tradiční i obnovitelné zdroje)",
      "Geodézie a kartografie",
      "Geologie a hornictví",
      "Hutnictví",
      "Hutnictví a metalurgie",
      "Inženýrství (stavební, strojní, chemické, elektro, průmyslové, výrobní)",
      "Jaderná energetika",
      "Konstrukce a strojírenství",
      "Mechanika a montáž",
      "Mechatronika",
      "Montážní a údržbářské práce",
      "Nábytkářství",
      "Obnovitelné zdroje energie",
      "Organizace a řízení výroby",
      "Stavebnictví",
      "Strojírenství",
      "Svářečství",
      "Textilní a oděvní průmysl",
      "Textilní průmysl",
      "Údržba a servis technologií",
      "Údržba technických zařízení",
      "Vodohospodářství",
      "Výroba (strojní, potravinářská, textilní, automobilová)",
      "Wind energy (větrná energetika)"
    ]
  },
  {
    label: "Obchod, Finance a Právo",
    options: [
      "Administrativa",
      "Bankovnictví",
      "Burzovnictví",
      "Bydlení a reality",
      "Cirkulární ekonomika",
      "Daňové poradenství",
      "Digitální marketing",
      "E-commerce",
      "Ekonomie",
      "Ekonomika a management",
      "Finance",
      "HR (lidské zdroje, personalistika)",
      "Inovační management",
      "Inspekční a kontrolní činnost",
      "Investiční poradenství",
      "Justiční služby",
      "Management",
      "Marketing",
      "Mezinárodní obchod",
      "Národní hospodářství",
      "Nemovitosti a reality",
      "Notářství",
      "Obchod a prodej",
      "Online marketing",
      "Personalistika",
      "Personalistika (HR)",
      "Podnikání",
      "Pojišťovnictví",
      "Právo",
      "Public relations (PR)",
      "Quality management (řízení kvality)",
      "Realitní činnost",
      "Reklama",
      "Řízení lidských zdrojů",
      "Soudnictví",
      "Účetnictví",
      "Účetnictví a daně",
      "Vztahy s veřejností"
    ]
  },
  {
    label: "Zdravotnictví, Ošetřovatelství a Sport",
    options: [
      "Celostní medicína",
      "Dermatologie (zdravotnictví)",
      "Farmacie",
      "Farmacie alternativní (bylinkářství, homeopatie)",
      "Farmakologie",
      "Fitness a sport",
      "Fyzioterapie",
      "Gymnastika a sportovní trenérství",
      "Histologie",
      "Kinanthropologie (věda o pohybu člověka)",
      "Lékárenství",
      "Lékařství",
      "Logopedie",
      "Medicína (klasická i alternativní)",
      "Neurovědy",
      "Nutriční terapie",
      "Nutriční vědy",
      "Oftalmologie",
      "Optika",
      "Optometrie",
      "Ortopedie",
      "Ošetřovatelství",
      "Psychologie",
      "Psychologie a terapie",
      "Radiologie",
      "Sport a tělovýchova",
      "Veterinářství",
      "Wellness a lázeňství",
      "Zdravotnictví",
      "Zubní lékařství"
    ]
  },
  {
    label: "Věda, Výzkum a Životní prostředí",
    options: [
      "Archeologie",
      "Biochemie",
      "Biologie",
      "Biotechnologie",
      "Chemie",
      "Ekologie a ochrana životního prostředí",
      "Ekologie a životní prostředí",
      "Fyzika",
      "Fyzika aplikovaná",
      "Geografie",
      "Geologie",
      "Historie",
      "Matematika",
      "Meteorologie",
      "Molekulární biologie",
      "Oceánografie",
      "Ochrana přírody",
      "Statistika",
      "Věda a výzkum",
      "Vědecký výzkum",
      "Xenobiologie (teoretický obor, výzkum života)",
      "Zoologie"
    ]
  },
  {
    label: "Umění, Design a Média",
    options: [
      "Architektura",
      "Audiovizuální tvorba",
      "Copywriting",
      "Dějiny umění",
      "Design (grafický, průmyslový, produktový, interiérový, UX/UI)",
      "Divadelní a filmová tvorba",
      "Dramaturgie a film",
      "Film a televize",
      "Fotografie",
      "Grafika a vizualizace",
      "Grafika (počítačová, umělecká, reklamní)",
      "Herectví a divadlo",
      "Hudba a hudební věda",
      "Hudba a umění",
      "Interiérový design",
      "Journalism (žurnalistika)",
      "Kulturní management",
      "Literatura",
      "Literatura a nakladatelství",
      "Loutkoherectví",
      "Média (TV, rádio, online média)",
      "Mediální studia",
      "Multimediální tvorba",
      "Muzejnictví",
      "Publikační činnost",
      "Restaurátorství",
      "Šperkařství",
      "Tisk a vydavatelství",
      "Umění (sochařství, malířství, hudba, dramatické)",
      "Výtvarnictví",
      "Výtvarné umění",
      "Xylografie (umělecké rytí do dřeva)",
      "Žurnalistika"
    ]
  },
  {
    label: "Služby, Gastronomie a Cestovní ruch",
    options: [
      "Catering",
      "Cestovní ruch",
      "Cukrářství",
      "Event management",
      "Gastronomie",
      "Gastronomie a pohostinství",
      "Hotelnictví",
      "Jachting a lodní doprava",
      "Kadeřnictví a kosmetické služby",
      "Kosmetologie",
      "Potravinářství",
      "Technologie potravin",
      "Turismus",
      "Vinařství",
      "Yachting (jachting a lodní služby)"
    ]
  },
  {
    label: "Vzdělávání, Humanitní vědy a Ostatní",
    options: [
      "Bohemistika (čeština, jazykověda)",
      "Bohosloví / Teologie",
      "Bohoslužby a duchovní péče",
      "Cizí jazyky a lingvistika",
      "Český jazyk a literatura",
      "Filosofie",
      "Historie a památková péče",
      "Humanitární činnost",
      "Jazyková výuka",
      "Jazykové služby (tlumočení, překlady, jazyková výuka)",
      "Jazykověda",
      "Knihovnictví a informační vědy",
      "Obnova památek",
      "Pedagogika",
      "Politologie",
      "Politologie a veřejná správa",
      "Regionální rozvoj",
      "Religionistika",
      "Sociologie",
      "Sociální služby",
      "Školství",
      "Teologie a církevní činnost",
      "Tlumočnictví a překladatelství",
      "Urbanismus a územní plánování",
      "Vzdělávání dospělých",
      "Youth work (práce s mládeží, volnočasové aktivity)"
    ]
  },
  {
    label: "Doprava, Logistika a Veřejná správa",
    options: [
      "Armáda a obrana",
      "Autodoprava",
      "Bezpečnostní služby",
      "Celní správa",
      "Doprava (silniční, železniční, letecká, námořní)",
      "Doprava a logistika",
      "Hasičství a záchranářství",
      "Kriminalistika",
      "Letectví a kosmonautika",
      "Logistika",
      "Logistika a skladování",
      "Námořní doprava",
      "Námořnictví",
      "Policie a bezpečnost",
      "Požární ochrana",
      "Provoz a doprava",
      "Transport a logistika",
      "Vojenské služby",
      "Železniční doprava"
    ]
  },
  {
    label: "Zemědělství a Řemesla",
    options: [
      "Agronomie",
      "Akvakultura",
      "Automechanik",
      "Čalounictví",
      "Instalace a údržba (instalatér, opravář)",
      "Kovářství",
      "Lesnictví",
      "Quarantine services (veterinární, hygienické)",
      "Řemesla (zedník, truhlář, instalatér, krejčí)",
      "Veterinární služby",
      "Zahradnictví",
      "Zemědělství"
    ]
  }
].map((group) => ({
  ...group,
  options: group.options.map((option) => ({ value: option, label: option }))
}));